---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: canopy-test-project
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: canopy-test-appset
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-gitops.git"
      revision: main
      files:
      - path: canopy/test/**/config.yaml
  template:
    metadata:
      name: "{{ .path.basename }}-test"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: USER_NAME-test
      project: canopy-test-project
      sources:
        - ref: app-values
          repoURL: "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-gitops.git"
          targetRevision: main
        - helm:
            valueFiles:
              - '{{ .values_file | default "$app-values/model-deployments/test/{{ .path.basename }}/config.yaml" }}'
          path: '{{ .chart_path }}'
          repoURL: '{{ .repo_url | default "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-helmcharts.git" }}'
          targetRevision: '{{ .target_revision | default "main" }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - Validate=true
