---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: genaiops-toolings-project
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: genaiops-toolings-appset
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-gitops.git"
      revision: main
      files:
      - path: toolings/**/config.yaml
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: USER_NAME-toolings
      project: genaiops-toolings-project
      sources:
        - ref: app-values
          repoURL: "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-gitops.git"
          targetRevision: main
        - helm:
            valueFiles:
              - $app-values/toolings/{{ .path.basename }}/config.yaml 
          path: '{{ .chart_path }}'
          repoURL: '{{ .repo_url | default "https://gitea-gitea.CLUSTER_DOMAIN/USER_NAME/genaiops-helmcharts.git" }}'
          targetRevision: '{{ .target_revision | default "main" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
